### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by m1911** [LeeHDsniper/AutoSqli#1]
./Autosqli.py:行13: application/json}: 没有那个文件或目录
./Autosqli.py:行15: 未预期的符号 `(' 附近有语法错误
./Autosqli.py:行15:`app=Flask(**name**)'
 这啥情况

**Comment by LeeHDsniper** [comment]
应该是第13—15行的代码有问题，第十三行：HEADER={'Content-Type': 'application/json'}的键、值都是字符串类型，要加上单引号，第15行app=Flask(__name__)最后面是没有单引号的。你再核对下代码看看，或者直接copy进去。

**Comment by LeeHDsniper** [comment]
应该是第13—15行的代码有问题，第十三行：HEADER={'Content-Type':
'application/json'}的键、值都是字符串类型，要加上单引号，第15行app=Flask(_name_
)最后面是没有单引号的。你再核对下代码看看，或者直接copy进去。

2016-04-11 10:31 GMT+08:00 m1911 notifications@github.com:

**Comment by m1911** [comment]
我知道了 要Python Autosqli.py 这个才行 我是直接./了

**Comment by m1911** [comment]
Quickly Bulid 把url放进去直接卡主 浏览器了

**Comment by LeeHDsniper** [comment]
你可以在运行Autosqli.py的终端里面看到运行时报告，看看哪里报错

2016-04-11 13:06 GMT+08:00 m1911 notifications@github.com:

**Comment by m1911** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chao/tools/autoSqli/autosqli.py", line 315, in handle_post_quickbuild
    taskid=new_Taskid()
  File "/home/chao/tools/autoSqli/autosqli.py", line 145, in new_Taskid
    responseData=json.loads(requests.get(url,None).text)
TypeError: get() takes exactly 1 argument (2 given)
快速创建的报错

**Comment by m1911** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chao/tools/autoSqli/autosqli.py", line 342, in handle_post_customtask
    taskid=new_Taskid()
  File "/home/chao/tools/autoSqli/autosqli.py", line 145, in new_Taskid
    responseData=json.loads(requests.get(url,None).text)
TypeError: get() takes exactly 1 argument (2 given)

这个是正常创建任务的时候

**Comment by c4bbage** [comment]
棒

**Comment by hehe321** [comment]
@m1911 你的问题解决了吗？

**Comment by LeeHDsniper** [comment]
有没有安装requests包？没有的话使用pip install requests安装
