### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by hehe321** [LeeHDsniper/AutoSqli#2]
快速创建的报错
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in call
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "/home/chao/tools/autoSqli/autosqli.py", line 315, in handle_post_quickbuild
taskid=new_Taskid()
File "/home/chao/tools/autoSqli/autosqli.py", line 145, in new_Taskid
responseData=json.loads(requests.get(url,None).text)
TypeError: get() takes exactly 1 argument (2 given)
快速创建的报错

**Comment by LeeHDsniper** [comment]
有没有安装requests包？没有的话使用pip install requests安装

**Comment by hehe321** [comment]
@LeeHDsniper 安装了，还是不行，一样的报错

**Comment by LeeHDsniper** [comment]
我昨晚试了，第一步，下载这个项目和sqlmap
第二步，pip install flask 和requests
第三步，复制sqlmap项目到/usr/lib/python2.7目录下
第三步，cd /usr/lib/python2.7/sqlmap-master
sudo python ./sqlmapapi.py -s
第四步，修改AutoSqli.py中开头的serverlist，设定为目前sqlmapapi运行地址
第五步，运行sudo python AutoSqli.py
然后就成功了。
看看你有没有遗漏，我也找不到问题出在哪，看报错应该是函数参数问题。但是我确实运行成功了。

**Comment by hehe321** [comment]
@LeeHDsniper 你第四步sqlmapapi的运行地址怎么改的？

**Comment by LeeHDsniper** [comment]
11行：SERVER_List=["http://127.0.0.1:8775"]
这个地址是sqlmapapi的默认运行地址

**Comment by hehe321** [comment]
还是不行，我用的是ubuntu 14.04，不知道是不是操作系统的问题

**Comment by LeeHDsniper** [comment]
和操作系统没有关系，应该是python版本的问题，我的是Python 2.7.11+。

**Comment by hehe321** [comment]
我用的是系统自带的Python 2.7.6

**Comment by GreyGY** [comment]
@LeeHDsniper 
E:\工具管理\注入\AutoSqli-master>python Autosqli.py
Traceback (most recent call last):
  File "Autosqli.py", line 554, in <module>
    init_Db()
  File "Autosqli.py", line 52, in init_Db
    db.commit()
  File "C:\Python27\lib\site-packages\flask\ctx.py", line 243, in __exit__
    self.pop(exc_value)
  File "C:\Python27\lib\site-packages\flask\ctx.py", line 231, in pop
    self.app.do_teardown_appcontext(exc)
  File "C:\Python27\lib\site-packages\flask\app.py", line 2166, in do_teardown_appcontext
    func(exc)
  File "Autosqli.py", line 61, in close_Db
    db=get_Db()
  File "Autosqli.py", line 45, in get_Db
    sqlite_db=connect_Db()
  File "Autosqli.py", line 41, in connect_Db
    rv=sqlite3.connect(app.config['DATABASE'])
sqlite3.OperationalError: unable to open database file
我运行的结果是数据库错误，请问该如何解决呢

**Comment by LeeHDsniper** [comment]
检查数据库文件路径是否存在

**Comment by GreyGY** [comment]
弄清楚了   是中文路径的问题
